language: c

compiler:
  - gcc
  - clang

dist: bionic

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    - os: linux
      arch: ppc64le

script: cd src && make tests
